services:
  app:
    build: .
    command: sh -c "yarn install && yarn run server-dev"
    ports:
      - 127.0.0.1:3000:3000
      - 127.0.0.1:6006:6006
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: lockerDB

  mysql:
    image: mysql:8.0
    volumes:
      - locker-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: lockerDB

volumes:
  locker-mysql-data:
